/**
 * Created by Emily on 24/04/14.
 */
//import java.io.*;
package skale.week3;
import java.util.*;

class Maink {
    public static void main(String[] args) {
        System.out.println("k");
        Scanner input = null;
        String line = input.nextLine();
    }
}
/*
class Task1 {
    int [] myArray = new int[3];
    myArray [2] = 3;    //assign a value to index 3

}
*/

/*
Try to assign a value for the element at index 3.
Run the program to see what happens.
Uncomment the code above and put them both into a try block.
Add two catch cases, one for a NullPointerException
and one for an ArrayIndexOutOfBoundsException.
In each block, print the name of the type of the exception caught.
Run the program to see what happens.
Then, switch the order of the catch cases. Run the program again.
Can you explain what is happening?

 */